Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "cent64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,

  # Machine Changes
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    #vb.customize ["modifyvm", :id, "--memory", "4096"]
    #vb.customize ["modifyvm", :id, "--cpus", 4]
  end

  # Folder Configs
  config.vm.synced_folder ".", "/opt/azphp", :mount_options => ["dmode=777","fmode=666"]

  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "172.16.0.11"


  #Run setup
  config.vm.provision :ansible do |ansible|
    ansible.limit = 'all'
    ansible.playbook = "vagrant.yml"
    ansible.inventory_path = "vagrant.hosts"
  end

end

