---

- name: Create SSH Directory
  file: path=/root/.ssh owner=root group=root mode=700 state=directory

- name: Copy over Deployment key | Private
  copy: src=secure/deploy.private owner=root group=root mode=600 dest=/root/.ssh/id_rsa

- name: Copy over Deployment key | Public
  copy: src=secure/deploy.public owner=root group=root mode=600 dest=/root/.ssh/id_rsa.pub 
